# Project information
site_name: Project Prometheus
site_url: https://rajtilakjee.github.io/prometheus
site_author: Rajtilak Bhattacharjee
site_description: >-
  Resources for self-learning Machine Learning.

# Repository
repo_name: rajtilakjee/prometheus
repo_url: https://github.com/rajtilakjee/prometheus

# Copyright
copyright: Copyright &copy; 2024 Rajtilak Bhattacharjee

# Configuration
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rajtilakjee
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/rajtilakjee

# Page tree
nav:
  - Home: index.md